port: 8888
mirakurunPath: http+unix://%2Fvar%2Frun%2Fmirakurun.sock/

#po:cmd
#pm2 status
#pm2 restart 0

#dbtype: sqlite
# sqlite:
#   extensions:
#     - '/hoge/regexp.dylib'
#   regexp: true

dbtype: mysql
mysql:
    host: 192.168.1.83
    port: 3306
    user: epgstation
    password: epgstation
    database: epgstation
    charset: utf8mb4

# 囲み文字を置換するか
needToReplaceEnclosingCharacters: true
#needToReplaceEnclosingCharacters: false

epgUpdateIntervalTime: 360


conflictPriority: 1
recPriority: 2

isEnabledDropCheck: true

recordedFormat: '%TITLE%-%YEAR%年%MONTH%月%DAY%日%HOUR%時'
recordedFileExtension: .ts
recorded:
    - name: recorded
      #path: '/srv/dev-disk-by-uuid-A6DA96A3DA966F75/NAS/Recorded/2024-1cours'
      #path: '/srv/dev-disk-by-uuid-D454C24354C22856/NAS_4_1/Recorded/2023-1cours'
      path: '/srv/dev-disk-by-uuid-D454C24354C22856/NAS_4_1/Recorded/2024-1cours'
    - name: recorded-2c
      path: '/srv/dev-disk-by-uuid-D454C24354C22856/NAS_4_1/Recorded/2024-2cours'
    - name: recorded-3c
      path: '/srv/dev-disk-by-uuid-D454C24354C22856/NAS_4_1/Recorded/2024-3cours'
    - name: recorded-4c
      path: '/srv/dev-disk-by-uuid-D454C24354C22856/NAS_4_1/Recorded/2024-4cours'
    - name: TV Program
      path: '/srv/dev-disk-by-uuid-A6DA96A3DA966F75/NAS/Recorded/TV_Program'
    - name: 再エンコード
      path: '/srv/dev-disk-by-uuid-A6DA96A3DA966F75/NAS/Recorded/TV_Program/2nd_encord'
    - name: movie
      path: '/srv/dev-disk-by-uuid-A6DA96A3DA966F75/NAS/Recorded/Movie'
    - name: 2023年春番組M2TS
      path: '/srv/dev-disk-by-uuid-A6DA96A3DA966F75/NAS/Recorded/2023年春番組M2TS'
    - name: 2023年夏番組M2TS
      path: '/srv/dev-disk-by-uuid-A6DA96A3DA966F75/NAS/Recorded/2023年夏番組M2TS'
    - name: subtitle
      path: '/srv/dev-disk-by-uuid-A6DA96A3DA966F75/NAS/Recorded/subtitle'
    - name: music
      path: '/srv/dev-disk-by-uuid-A6DA96A3DA966F75/NAS/Recorded/Podcast/music'
    - name: Blu-ray
      path: '/srv/dev-disk-by-uuid-10123343e9acbce6'

thumbnail: '/srv/dev-disk-by-uuid-A6DA96A3DA966F75/NAS/Recorded/thumbnail'
thumbnailSize: 480x270
thumbnailPosition: 30

ffmpeg: /usr/bin/ffmpeg
ffprobe: /usr/bin/ffprobe
#ffmpeg: /usr/local/bin/ffmpeg
#ffprobe: /usr/local/bin/ffprobe

encodeProcessNum: 4
concurrentEncodeNum: 1
encode:
    #- name: CMCUT-10M
    #  cmd: '%NODE% %ROOT%/config/enc-cm-enh.js'
    #  suffix: .mp4
    #  rate: 4.0

    - name: CMCUT-10M #-MAIN
      cmd: '%NODE% %ROOT%/config/enc-cm-enh-main.js'
      suffix: .mp4
      rate: 20.0

    - name: CMCUT-3M
      cmd: '%NODE% %ROOT%/config/enc-cm-enh-low.js'
      suffix: .mp4
      rate: 4.0
    
    #- name: CMCUT-10M-ATX
    #  cmd: '%NODE% %ROOT%/config/enc-cm-enh-ATX.js'
    #  suffix: .mp4
   #  rate: 4.0

    - name: CMCUT-10M-ATX-ac6
      cmd: '%NODE% %ROOT%/config/enc-cm-enh-ATX-ac6.js'
      suffix: .mp4
      rate: 4.0

    #- name: CMCUT-INLOGO-10M
    #  cmd: '%NODE% %ROOT%/config/enc-cm-inlogo-enh-10M.js'
    #  suffix: .mp4
    #  rate: 4.0

    #- name: CMCUT-INLOGO-3M
    #  cmd: '%NODE% %ROOT%/config/enc-cm-inlogo-enh-3M.js'
    #  suffix: .mp4
    #  rate: 4.0

    #- name: H.264-ac6-10M
    #  cmd: '%NODE% %ROOT%/config/enc-enhance-ac6-10M.js'
    #  suffix: .mp4
    #  rate: 4.0

    #- name: H.264-ac6-3M
    #  cmd: '%NODE% %ROOT%/config/enc-enhance-ac6-3M.js'
    #  suffix: .mp4
    #  rate: 4.0

    #- name: H.264-10M
    #  cmd: '%NODE% %ROOT%/config/enc-enhance.js'
    #  suffix: .mp4
    #  rate: 4.0

    #- name: H.264-3M
    #  cmd: '%NODE% %ROOT%/config/enc-enhance-low.js'
    #  suffix: .mp4
    #  rate: 4.0

    - name: subtitle-SRT
      cmd: '%NODE% %ROOT%/config/subtitle.js'
      suffix: .jpn.srt
      rate: 4.0

    - name: CM-subtitle-SRT
      cmd: '/bin/bash %ROOT%/config/cm-subtitle-12.sh'
      suffix: _cmcut.jpn.srt
      rate: 4.0

    #- name: CM-subtitle-SRT-MP4
    #  cmd: '/bin/bash %ROOT%/config/cm-subtitle-mp4.sh'
    #  suffix: _cmcut.jpn.srt
    #  rate: 4.0
    
    #- name: podcast
    #  cmd: '%NODE% %ROOT%/config/podcast.js'
    #  suffix: .aac
    #  rate: 4.0   

    #- name: podcast-video
    #  cmd: '%NODE% %ROOT%/config/podcast-low-mp4.js'
    #  suffix: .mp4
    #  rate: 4.0   

urlscheme:
    m2ts:
        ios: vlc-x-callback://x-callback-url/stream?url=PROTOCOL%3A%2F%2FADDRESS
        android: intent://ADDRESS#Intent;action=android.intent.action.VIEW;type=video/*;scheme=PROTOCOL;end
        win: 'cvlc://PROTOCOL://ADDRESS'
    video:
        ios: infuse://x-callback-url/play?url=PROTOCOL://ADDRESS
        android: intent://ADDRESS#Intent;action=android.intent.action.VIEW;type=video/*;scheme=PROTOCOL;end
        win: 'cvlc://PROTOCOL://ADDRESS'
    download:
        ios: vlc-x-callback://x-callback-url/download?url=PROTOCOL%3A%2F%2FADDRESS&filename=FILENAME

stream:
    live:
        ts:
            m2ts:
                - name: 720p
                  cmd:
                      '%FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2
                      -c:v h264_v4l2m2m -vf yadif,scale=-2:720 -b:v 3000k -preset veryfast -y -f mpegts pipe:1'
                - name: 480p
                  cmd:
                      '%FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 128k -ac 2
                      -c:v h264_v4l2m2m  -b:v 1500k -preset veryfast -y -f mpegts pipe:1'
                      #-vf yadif,scale=-2:480
                - name: 無変換

            m2tsll:
                - name: 720p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -f mpegts -analyzeduration 500000 -i pipe:0 -map 0 -c:s copy -c:d
                      copy -ignore_unknown -fflags nobuffer -flags low_delay -max_delay 250000 -max_interleave_delta 1
                      -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2 -c:v h264_v4l2m2m -flags +cgop -vf yadif,scale=-2:720
                      -b:v 3000k -preset veryfast -y -f mpegts pipe:1'
                - name: 480p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -f mpegts -analyzeduration 500000 -i pipe:0 -map 0 -c:s copy -c:d
                      copy -ignore_unknown -fflags nobuffer -flags low_delay -max_delay 250000 -max_interleave_delta 1
                      -threads 0 -c:a aac -ar 48000 -b:a 128k -ac 2 -c:v h264_v4l2m2m -flags +cgop -vf yadif,scale=-2:480
                      -b:v 1500k -preset veryfast -y -f mpegts pipe:1'

            webm:
                - name: 720p
                  cmd:
                      '%FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -threads 3 -c:a libvorbis -ar 48000 -b:a 192k -ac
                      2 -c:v libvpx-vp9 -vf yadif,scale=-2:720 -b:v 3000k -deadline realtime -speed 4 -cpu-used -8 -y -f
                      webm pipe:1'
                - name: 480p
                  cmd:
                      '%FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -threads 2 -c:a libvorbis -ar 48000 -b:a 128k -ac
                      2 -c:v libvpx-vp9 -vf yadif,scale=-2:480 -b:v 1500k -deadline realtime -speed 4 -cpu-used -8 -y -f
                      webm pipe:1'

            mp4:
                - name: 720p
                  cmd:
                      '%FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2
                      -c:v h264_v4l2m2m -vf yadif,scale=-2:720 -b:v 3000k -profile:v baseline -preset veryfast -tune
                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4
                      pipe:1'
                - name: 480p
                  cmd:
                      '%FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 128k -ac 2
                      -c:v h264_v4l2m2m -b:v 1500k -profile:v baseline -tune
                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4
                      pipe:1'
                - name: H264-ENH
                  cmd:
                      '%FFMPEG% -re -i pipe:0 -threads 0 -c:a copy -bsf:a aac_adtstoasc -c:v h264_v4l2m2m -vb 3000k 
                      -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4 pipe:1'
                
            hls:
                - name: 720p
                  cmd:
                      '%FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -map 0 -threads 0 -ignore_unknown
                      -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 17 -hls_allow_cache 1
                      -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a
                      aac -ar 48000 -b:a 192k -ac 2 -c:v libx264 -vf yadif,scale=-2:720 -b:v 3000k -preset veryfast
                      -flags +loop-global_header %OUTPUT%'
                - name: 480p
                  cmd:
                      '%FFMPEG% -re -dual_mono_mode main -i pipe:0 -sn -map 0 -threads 0 -ignore_unknown
                      -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 17 -hls_allow_cache 1 
                      -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a
                      aac -ar 48000 -b:a 128k -ac 2 -c:v libx264 -vf yadif,scale=-2:480 -b:v 1500k -preset veryfast
                      -flags +loop-global_header %OUTPUT%'
                # - name: 720p (arib)
                #   cmd:
                #       '%FFMPEG% -re -dual_mono_mode main -fix_sub_duration -i pipe:0 -threads 0 -ignore_unknown
                #       -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 17 -hls_allow_cache 1
                #       -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a
                #       aac -ar 48000 -b:a 192k -ac 2 -c:v h264_v4l2m2m -vf yadif,scale=-2:720 -b:v 3000k -preset veryfast
                #       -flags +loop-global_header -c:s webvtt -master_pl_name stream%streamNum%.m3u8
                #       %streamFileDir%/stream%streamNum%-child.m3u8'

    recorded:
        ts:
            webm:
                - name: 720p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 3 -c:a libvorbis -ar 48000 -b:a 192k -ac 2
                      -c:v libvpx-vp9 -vf yadif,scale=-2:720 -b:v 3000k -deadline realtime -speed 4 -cpu-used -8 -y -f
                      webm pipe:1'
                - name: 480p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 3 -c:a libvorbis -ar 48000 -b:a 128k -ac 2
                      -c:v libvpx-vp9 -vf yadif,scale=-2:480 -b:v 1500k -deadline realtime -speed 4 -cpu-used -8 -y -f
                      webm pipe:1'

            mp4:
                - name: 720p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac 2 -c:v
                      h264_v4l2m2m -vf yadif,scale=-2:720 -b:v 3000k -profile:v baseline -preset veryfast -tune
                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4
                      pipe:1'
                - name: 480p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -i pipe:0 -sn -threads 0 -c:a aac -ar 48000 -b:a 128k -ac 2 -c:v
                      h264_v4l2m2m -vf yadif,scale=-2:480 -b:v 1500k -profile:v baseline -preset veryfast -tune
                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4
                      pipe:1'

            hls:
                - name: 720p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -i pipe:0 -sn -map 0 -threads 0 -ignore_unknown
                      -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1
                      -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a
                      aac -ar 48000 -b:a 192k -ac 2 -c:v h264_v4l2m2m -vf yadif,scale=-2:720 -b:v 3000k -preset veryfast
                      -flags +loop-global_header %OUTPUT%'
                - name: 480p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -i pipe:0 -sn -map 0 -threads 0 -ignore_unknown
                      -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1
                      -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a
                      aac -ar 48000 -b:a 128k -ac 2 -c:v h264_v4l2m2m -aspect 16:9 -b:v 1500k -preset veryfast
                      -flags +loop-global_header %OUTPUT%'
                # - name: 720p (arib)
                #   cmd:
                #       '%FFMPEG% -dual_mono_mode main -fix_sub_duration -i pipe:0 -threads 0 -ignore_unknown
                #       -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1
                #       -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a
                #       aac -ar 48000 -b:a 192k -ac 2 -c:v h264_v4l2m2m -vf yadif,scale=-2:720 -b:v 3000k -preset veryfast
                #       -flags +loop-global_header -c:s webvtt -master_pl_name stream%streamNum%.m3u8
                #       %streamFileDir%/stream%streamNum%-child.m3u8'

        encoded:
            webm:
                - name: 720p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 3 -c:a libvorbis -ar 48000 -b:a
                      192k -ac 2 -c:v libvpx-vp9 -vf scale=-2:720 -b:v 3000k -deadline realtime -speed 4 -cpu-used -8 -y
                      -f webm pipe:1'
                - name: 480p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 3 -c:a libvorbis -ar 48000 -b:a
                      128k -ac 2 -c:v libvpx-vp9 -vf scale=-2:480 -b:v 1500k -deadline realtime -speed 4 -cpu-used -8 -y
                      -f webm pipe:1'

            mp4:
                - name: 720p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 0 -c:a aac -ar 48000 -b:a 192k -ac
                      2 -c:v h264_v4l2m2m -vf scale=-2:720 -b:v 3000k -profile:v baseline -preset veryfast -tune
                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4
                      pipe:1'
                - name: 480p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 0 -c:a aac -ar 48000 -b:a 128k -ac
                      2 -c:v h264_v4l2m2m -vf scale=-2:480 -b:v 1500k -profile:v baseline -preset veryfast -tune
                      fastdecode,zerolatency -movflags frag_keyframe+empty_moov+faststart+default_base_moof -y -f mp4
                      pipe:1'
                - name: h264_v4l2m2m
                  cmd:
                      '%FFMPEG% -i %INPUT% -c:v h264_v4l2m2m -b:v 3M -y -f mp4 pipe:1'

            hls:
                - name: 720p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 0 -ignore_unknown
                      -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1
                      -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a
                      aac -ar 48000 -b:a 192k -ac 2 -c:v h264_v4l2m2m -vf scale=-2:720 -b:v 3000k -preset veryfast -flags
                      +loop-global_header %OUTPUT%'
                - name: 480p
                  cmd:
                      '%FFMPEG% -dual_mono_mode main -ss %SS% -i %INPUT% -sn -threads 0 -ignore_unknown
                      -max_muxing_queue_size 1024 -f hls -hls_time 3 -hls_list_size 0 -hls_allow_cache 1
                      -hls_segment_filename %streamFileDir%/stream%streamNum%-%09d.ts -hls_flags delete_segments -c:a
                      aac -ar 48000 -b:a 128k -ac 2 -c:v h264_v4l2m2m -vf scale=-2:480 -b:v 3000k -preset veryfast -flags
                      +loop-global_header %OUTPUT%'


reserveNewAddtionCommand: '/bin/sh %ROOT%/config/run_update.sh reserve -'
reserveUpdateCommand: '/bin/sh %ROOT%/config/run_update.sh update -'
reservedeletedCommand: '/bin/sh %ROOT%/config/run_update.sh delete -'
recordingPreStartCommand: '/bin/sh %ROOT%/config/run_prime.sh prestart -'
recordingPrepRecFailedCommand: '/bin/sh %ROOT%/config/run_prime.sh prepfailed -'
recordingStartCommand: '/bin/sh %ROOT%/config/run_prime.sh start -'
recordingFinishCommand: '/bin/sh %ROOT%/config/run_prime.sh end -'
recordingFailedCommand: '/bin/sh %ROOT%/config/run_prime.sh recfailed -'
encodingFinishCommand: '/bin/sh %ROOT%/config/run_encode.sh encod_end -'
